# Generated by Django 4.2.2 on 2023-06-12 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('population', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='President',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('image', models.ImageField(upload_to='presidents/')),
                ('genre', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme')], max_length=1)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pays')),
            ],
        ),
    ]
